import type { Product, Order, AppUser, Coupon } from "@/types";

/**
 * In-memory catalog used when DATABASE_URL is not configured.
 * Replace by hitting the Prisma client (see lib/db.ts) once MySQL is wired up.
 */

const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=70`;

export const PRODUCTS: Product[] = [
  {
    id: "p_001",
    slug: "florence-tote-cognac",
    name: "Florence Tote",
    tagline: "Precision-crafted in cognac full-grain leather.",
    description:
      "The Florence Tote is built around a single sheet of full-grain Tuscan leather, finished with edge-painted seams and solid brass hardware. Designed to age — not wear out.",
    price: 5500,
    compareAt: 6800,
    currency: "PKR",
    category: "tote",
    collection: "heritage",
    colors: ["Cognac", "Black", "Sand"],
    materials: ["Full-grain leather", "Brass hardware", "Cotton lining"],
    images: [
      img("photo-1548036328-c9fa89d128fa"),
      img("photo-1591561954557-26941169b49e"),
      img("photo-1590874103328-eac38a683ce7"),
    ],
    stock: 12,
    featured: true,
    rating: 4.8,
    reviewCount: 132,
    createdAt: "2026-04-12T10:00:00.000Z",
  },
  {
    id: "p_002",
    slug: "atelier-backpack-noir",
    name: "Atelier Backpack",
    tagline: "Quietly engineered for the studio commute.",
    description:
      "A clean-lined backpack with a padded laptop sleeve, water-resistant lining, and a magnetic roll-top closure. The pared-back silhouette hides obsessive interior organisation.",
    price: 5900,
    compareAt: 7500,
    currency: "PKR",
    category: "backpack",
    colors: ["Noir", "Stone"],
    materials: ["Coated canvas", "Italian leather trim"],
    images: [
      img("photo-1553062407-98eeb64c6a62"),
      img("photo-1581605405669-fcdf81165afa"),
      img("photo-1622560480605-d83c853bc5c3"),
    ],
    stock: 8,
    featured: true,
    rating: 4.7,
    reviewCount: 87,
    createdAt: "2026-03-20T10:00:00.000Z",
  },
  {
    id: "p_003",
    slug: "soiree-clutch-ivory",
    name: "Soirée Clutch",
    tagline: "An evening piece, cut from pearled calf.",
    description:
      "A slim, structured clutch with a hand-applied pearl finish and a single magnetic closure. Sized for a phone, key, and two cards — nothing more.",
    price: 3500,
    compareAt: 4500,
    currency: "PKR",
    category: "clutch",
    collection: "evening",
    colors: ["Ivory", "Champagne", "Onyx"],
    materials: ["Pearled calf leather", "Silk lining"],
    images: [
      img("photo-1566150905458-1bf1fc113f0d"),
      img("photo-1584917865442-de89df76afd3"),
    ],
    stock: 22,
    rating: 4.6,
    reviewCount: 54,
    createdAt: "2026-05-02T10:00:00.000Z",
  },
  {
    id: "p_004",
    slug: "courier-crossbody-tan",
    name: "Courier Crossbody",
    tagline: "Built for the city, finished for the gallery.",
    description:
      "A compact crossbody with adjustable strap, twin interior compartments, and our signature edge-painted finish. A daily piece that travels well.",
    price: 4200,
    currency: "PKR",
    category: "crossbody",
    colors: ["Tan", "Espresso"],
    materials: ["Vegetable-tanned leather"],
    images: [
      img("photo-1591348278863-a8fb3887e2aa"),
      img("photo-1564422170194-896b89110ef8"),
    ],
    stock: 16,
    featured: true,
    rating: 4.9,
    reviewCount: 211,
    createdAt: "2026-04-22T10:00:00.000Z",
  },
  {
    id: "p_005",
    slug: "weekend-duffel-olive",
    name: "Weekend Duffel",
    tagline: "Two nights, one bag, room to spare.",
    description:
      "A weekender cut from waxed canvas with full-grain leather handles, a shoe pocket, and an inner zip pouch. Stowable in any overhead bin.",
    price: 6500,
    compareAt: 8000,
    currency: "PKR",
    category: "duffel",
    colors: ["Olive", "Charcoal"],
    materials: ["Waxed canvas", "Full-grain leather", "Solid brass"],
    images: [
      img("photo-1553062407-98eeb64c6a62"),
      img("photo-1581605405669-fcdf81165afa"),
    ],
    stock: 5,
    rating: 4.7,
    reviewCount: 39,
    createdAt: "2026-02-15T10:00:00.000Z",
  },
  {
    id: "p_006",
    slug: "bifold-wallet-walnut",
    name: "Bifold Wallet",
    tagline: "A minimalist's daily carry.",
    description:
      "Six card slots, a bill pocket, and an interior coin pouch. Wrapped in walnut full-grain leather that softens beautifully with use.",
    price: 2000,
    currency: "PKR",
    category: "wallet",
    colors: ["Walnut", "Noir"],
    materials: ["Full-grain leather", "Cotton stitching"],
    images: [
      img("photo-1606513542745-97629752a13b"),
      img("photo-1572569511254-d8f925fe2cbb"),
    ],
    stock: 40,
    rating: 4.5,
    reviewCount: 312,
    createdAt: "2026-01-10T10:00:00.000Z",
  },
  {
    id: "p_007",
    slug: "milano-shoulder-noir",
    name: "Milano Shoulder",
    tagline: "Restrained Italian tailoring in leather.",
    description:
      "A clean shoulder bag with a gold-tone clasp, fully lined interior, and a removable pouch. Designed for evenings that begin at galleries.",
    price: 8000,
    currency: "PKR",
    category: "crossbody",
    collection: "evening",
    colors: ["Noir", "Bordeaux"],
    materials: ["Smooth calf leather", "Gold-tone hardware"],
    images: [
      img("photo-1584917865442-de89df76afd3"),
      img("photo-1559563458-527698bf5295"),
    ],
    stock: 7,
    featured: true,
    rating: 4.9,
    reviewCount: 64,
    createdAt: "2026-05-12T10:00:00.000Z",
  },
  {
    id: "p_008",
    slug: "voyager-tote-sand",
    name: "Voyager Tote",
    tagline: "Open-top tote for studio days.",
    description:
      "A relaxed, soft-structured tote with a generous interior, twin slip pockets, and a magnetic closure. Cut from supple sand-tone leather.",
    price: 5000,
    currency: "PKR",
    category: "tote",
    colors: ["Sand", "Black"],
    materials: ["Pebbled leather", "Suede lining"],
    images: [
      img("photo-1590874103328-eac38a683ce7"),
      img("photo-1548036328-c9fa89d128fa"),
    ],
    stock: 14,
    rating: 4.6,
    reviewCount: 78,
    createdAt: "2026-03-05T10:00:00.000Z",
  },
  {
    id: "p_009",
    slug: "studio-crossbody-rust",
    name: "Studio Crossbody",
    tagline: "Compact daily, cut from rust pebbled leather.",
    description:
      "A small-format crossbody with adjustable strap, slim profile, and a single magnetic flap. The kind of bag you reach for on a quick coffee run.",
    price: 3800,
    currency: "PKR",
    category: "crossbody",
    colors: ["Rust", "Black", "Stone"],
    materials: ["Pebbled leather", "Brass hardware"],
    images: [
      img("photo-1564422170194-896b89110ef8"),
      img("photo-1559563458-527698bf5295"),
    ],
    stock: 18,
    featured: true,
    rating: 4.6,
    reviewCount: 64,
    createdAt: "2026-05-18T10:00:00.000Z",
  },
  {
    id: "p_010",
    slug: "heritage-cardholder-noir",
    name: "Heritage Cardholder",
    tagline: "Eight cards. One pocket. No bulk.",
    description:
      "A flat cardholder with eight slots, a center bill compartment, and our atelier mark embossed inside. Carried as easily in a coat as in a back pocket.",
    price: 1800,
    compareAt: 2500,
    currency: "PKR",
    category: "wallet",
    colors: ["Noir", "Cognac"],
    materials: ["Full-grain leather"],
    images: [
      img("photo-1572569511254-d8f925fe2cbb"),
      img("photo-1606513542745-97629752a13b"),
    ],
    stock: 50,
    rating: 4.4,
    reviewCount: 198,
    createdAt: "2026-01-22T10:00:00.000Z",
  },
  {
    id: "p_011",
    slug: "voyage-weekender-tan",
    name: "Voyage Weekender",
    tagline: "Cabin-sized, leather-trimmed, ready to travel.",
    description:
      "Slightly larger than our Duffel — a leather-trimmed canvas weekender designed for three-night trips. Two-tone with chocolate handles.",
    price: 7500,
    currency: "PKR",
    category: "duffel",
    collection: "heritage",
    colors: ["Tan", "Slate"],
    materials: ["Twill canvas", "Full-grain leather", "YKK zips"],
    images: [
      img("photo-1547949003-9792a18a2601"),
      img("photo-1553062407-98eeb64c6a62"),
    ],
    stock: 9,
    featured: true,
    rating: 4.8,
    reviewCount: 52,
    createdAt: "2026-04-30T10:00:00.000Z",
  },
  {
    id: "p_012",
    slug: "minute-clutch-bordeaux",
    name: "Minute Clutch",
    tagline: "A clutch for the last hour of the night.",
    description:
      "Hand-sized, with a delicate chain that hides inside when not in use. Slip in a card, key, and the obvious lipstick — nothing else fits.",
    price: 3200,
    compareAt: 4200,
    currency: "PKR",
    category: "clutch",
    collection: "evening",
    colors: ["Bordeaux", "Onyx"],
    materials: ["Satin-finish leather", "Brass chain"],
    images: [
      img("photo-1584917865442-de89df76afd3"),
      img("photo-1566150905458-1bf1fc113f0d"),
    ],
    stock: 11,
    rating: 4.7,
    reviewCount: 41,
    createdAt: "2026-05-25T10:00:00.000Z",
  },
  {
    id: "p_013",
    slug: "carry-backpack-stone",
    name: "Carry Backpack",
    tagline: "Lightweight commuter in stone canvas.",
    description:
      "A trim, lightweight backpack with a quick-access top pocket, padded back panel, and a laptop sleeve fit for a 14-inch machine.",
    price: 4500,
    currency: "PKR",
    category: "backpack",
    colors: ["Stone", "Noir"],
    materials: ["Recycled canvas", "Leather trim"],
    images: [
      img("photo-1581605405669-fcdf81165afa"),
      img("photo-1622560480605-d83c853bc5c3"),
    ],
    stock: 22,
    featured: true,
    rating: 4.5,
    reviewCount: 73,
    createdAt: "2026-02-28T10:00:00.000Z",
  },
];

// Seed a couple of reviews on the first products
PRODUCTS[0].reviews = [
  {
    id: "r1",
    author: "Mira K.",
    userId: "u_001",
    rating: 5,
    title: "Worth every penny",
    body: "The stitching is precise and the leather smells incredible. Already wearing the patina I hoped for.",
    images: [],
    createdAt: "2026-05-21T10:00:00.000Z",
  },
  {
    id: "r2",
    author: "Daniel R.",
    userId: "u_002",
    rating: 4,
    title: "Beautiful, but heavy",
    body: "Build quality is exceptional. A touch heavy when fully loaded, but that is the price of leather this thick.",
    images: [],
    createdAt: "2026-04-15T10:00:00.000Z",
  },
];

export const ORDERS: Order[] = [
  {
    id: "ord_1024",
    userId: "u_001",
    customerName: "Mira Kapoor",
    customerEmail: "mira@example.com",
    items: [
      {
        productId: "p_001",
        slug: "florence-tote-cognac",
        name: "Florence Tote",
        image: PRODUCTS[0].images[0],
        price: 5500,
        quantity: 1,
        color: "Cognac",
      },
    ],
    subtotal: 5500,
    shipping: 250,
    tax: 0,
    total: 5750,
    status: "shipped",
    paymentMethod: "cod",
    createdAt: "2026-06-12T10:00:00.000Z",
  },
  {
    id: "ord_1025",
    userId: "u_002",
    customerName: "Daniel Reyes",
    customerEmail: "daniel@example.com",
    items: [
      {
        productId: "p_002",
        slug: "atelier-backpack-noir",
        name: "Atelier Backpack",
        image: PRODUCTS[1].images[0],
        price: 7500,
        quantity: 1,
      },
      {
        productId: "p_006",
        slug: "bifold-wallet-walnut",
        name: "Bifold Wallet",
        image: PRODUCTS[5].images[0],
        price: 2000,
        quantity: 2,
      },
    ],
    subtotal: 11500,
    shipping: 250,
    tax: 0,
    total: 11750,
    status: "paid",
    paymentMethod: "card",
    createdAt: "2026-06-18T10:00:00.000Z",
  },
  {
    id: "ord_1026",
    userId: "u_003",
    customerName: "Asha Verma",
    customerEmail: "asha@example.com",
    items: [
      {
        productId: "p_007",
        slug: "milano-shoulder-noir",
        name: "Milano Shoulder",
        image: PRODUCTS[6].images[0],
        price: 8000,
        quantity: 1,
      },
    ],
    subtotal: 8000,
    shipping: 250,
    tax: 0,
    total: 8250,
    status: "pending",
    paymentMethod: "cod",
    createdAt: "2026-06-22T10:00:00.000Z",
  },
];

export const USERS: AppUser[] = [
  {
    id: "u_admin",
    name: "BagsArt Admin",
    email: "bags.art.pk@gmail.com",
    role: "admin",
    createdAt: "2026-01-01T00:00:00.000Z",
    ordersCount: 0,
  },
  {
    id: "u_001",
    name: "Mira Kapoor",
    email: "mira@example.com",
    role: "customer",
    createdAt: "2026-02-12T00:00:00.000Z",
    ordersCount: 1,
  },
  {
    id: "u_002",
    name: "Daniel Reyes",
    email: "daniel@example.com",
    role: "customer",
    createdAt: "2026-03-04T00:00:00.000Z",
    ordersCount: 1,
  },
  {
    id: "u_003",
    name: "Asha Verma",
    email: "asha@example.com",
    role: "customer",
    createdAt: "2026-04-18T00:00:00.000Z",
    ordersCount: 1,
  },
];

export const COUPONS: Coupon[] = [
  { code: "WELCOME10", type: "percent", value: 10, active: true, uses: 142 },
  { code: "STUDIO25", type: "percent", value: 25, active: true, uses: 18 },
  { code: "SHIP", type: "fixed", value: 15, active: false, uses: 320 },
];

export const TESTIMONIALS = [
  {
    name: "Naomi Aldridge",
    role: "Editor, Studio Magazine",
    quote:
      "BagsArt is the rare label that feels both quiet and confident. The Florence Tote is the only bag I've carried daily for six months.",
  },
  {
    name: "Idris Khoury",
    role: "Architect",
    quote:
      "The hardware on my Atelier Backpack still feels new after a year of commuting. Beautifully understated design.",
  },
  {
    name: "Léa Sorrentino",
    role: "Gallerist, Milan",
    quote:
      "I bought the Milano Shoulder for a single opening. I haven't carried anything else to one since.",
  },
];

export const CATEGORIES = [
  { slug: "tote", label: "Totes", image: img("photo-1548036328-c9fa89d128fa") },
  { slug: "backpack", label: "Backpacks", image: img("photo-1553062407-98eeb64c6a62") },
  { slug: "crossbody", label: "Crossbody", image: img("photo-1584917865442-de89df76afd3") },
  { slug: "clutch", label: "Clutches", image: img("photo-1566150905458-1bf1fc113f0d") },
  { slug: "duffel", label: "Duffels", image: img("photo-1547949003-9792a18a2601") },
  { slug: "wallet", label: "Wallets", image: img("photo-1606513542745-97629752a13b") },
];
